FROM local/buildkite-remote-docker:latest

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    apk add --no-cache \
    openrc=0.41.2-r1 \
    docker=19.03.2-r0 && \
    rc-update add docker boot

VOLUME /buildkite
WORKDIR /buildkite
ENTRYPOINT ["buildkite-agent"]
CMD ["start"]
