steps:
  - label: lint
    agents:
      queue: bootstrap
    commands:
      - "hadolint Dockerfile"
  - label: build
    agents:
      queue: bootstrap
    commands:
      - "echo $NITE"
      - "docker build -t test/buildkite-remote-docker:$BUILDKITE_COMMIT ."
