steps:
  - label: lint
    agents:
      queue: bootstrap
    commands:
      - "hadolint Dockerfile"
  - label: build
    agents:
      queue: bootstrap
    commands:
      - "docker build -t test/buildkite-remote-docker:$BUILDKITE_COMMIT ."


# steps:
#   - command:
#       - "yarn install"
#       - "yarn run test"
#     plugins:
#       - docker#v3.3.0:
#           image: "node:7"
#           always-pull: true
#           environment:
#             - "MY_SECRET_KEY"
#             - "MY_SPECIAL_BUT_PUBLIC_VALUE=kittens"
#
#
# steps:
#   - command:
#       - "yarn install"
#       - "yarn run test"
#     env:
#       MY_SPECIAL_BUT_PUBLIC_VALUE: kittens
#     plugins:
#       - docker#v3.3.0:
#           image: "node:7"
#           always-pull: true
#           propagate-environment: true
#
# steps:
#   - commands:
#       - "docker build . -t image:tag"
#       - "docker push image:tag"
#     plugins:
#       - docker#v3.3.0:
#           image: "docker:latest"
#           always-pull: true
#           volumes:
#             - "/var/run/docker.sock:/var/run/docker.sock"
