steps:
  - label: lint
    agents:
      queue: bootstrap
    commands:
      - "hadolint Dockerfile"
  - label: build
    agents:
      queue: bootstrap
    commands:
      - "echo $NITE"
      - "docker build -t test/buildkite-remote-docker:$BUILDKITE_COMMIT ."
  - label: publish
    agents:
      queue: bootstrap
    commands:
      - "ls -la .."
      - "echo $NITE"
      - "echo $NITETIME"
      #- "echo $QUAY_DEPLOY_PASSWORD | docker login -u $QUAY_DEPLOY_USER --password-stdin quay.io"
